### ISSUE TITLE
DLM on the master branch doesn't run

### ISSUE THREAD

**Issue by Zhen-hao** [stripe/rainier#152]
```
Exception in thread "main" java.lang.NoClassDefFoundError: com/stripe/rainier/internal/asm/tree/MethodNode
	at com.stripe.rainier.ir.MethodGenerator.methodNode(MethodGenerator.scala:16)
	at com.stripe.rainier.ir.MethodGenerator.methodNode$(MethodGenerator.scala:15)
	at com.stripe.rainier.ir.ExprMethodGenerator.methodNode$lzycompute(ExprMethodGenerator.scala:3)
	at com.stripe.rainier.ir.ExprMethodGenerator.methodNode(ExprMethodGenerator.scala:3)
	at com.stripe.rainier.ir.MethodGenerator.loadParams(MethodGenerator.scala:137)
	at com.stripe.rainier.ir.MethodGenerator.loadParams$(MethodGenerator.scala:136)
	at com.stripe.rainier.ir.ExprMethodGenerator.loadParams(ExprMethodGenerator.scala:3)
	at com.stripe.rainier.ir.MethodGenerator.loadParameter(MethodGenerator.scala:59)
	at com.stripe.rainier.ir.MethodGenerator.loadParameter$(MethodGenerator.scala:58)
	at com.stripe.rainier.ir.ExprMethodGenerator.loadParameter(ExprMethodGenerator.scala:3)
	at com.stripe.rainier.ir.ExprMethodGenerator.traverse(ExprMethodGenerator.scala:24)
	at com.stripe.rainier.ir.ExprMethodGenerator.traverse(ExprMethodGenerator.scala:26)
	at com.stripe.rainier.ir.ExprMethodGenerator.<init>(ExprMethodGenerator.scala:16)
	at com.stripe.rainier.ir.CompiledFunction$.$anonfun$apply$2(CompiledFunction.scala:31)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:320)
	at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:976)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:47)
	at scala.collection.SetLike.map(SetLike.scala:101)
	at scala.collection.SetLike.map$(SetLike.scala:101)
	at scala.collection.AbstractSet.map(Set.scala:47)
	at com.stripe.rainier.ir.CompiledFunction$.apply(CompiledFunction.scala:26)
	at com.stripe.rainier.compute.IRCompiler.compileUnsafe(Compiler.scala:72)
	at com.stripe.rainier.compute.Compiler.compile(Compiler.scala:13)
	at com.stripe.rainier.compute.Compiler.compile$(Compiler.scala:11)
	at com.stripe.rainier.compute.IRCompiler.compile(Compiler.scala:55)
	at com.stripe.rainier.core.Sampleable.prepare(Sampleable.scala:26)
	at com.stripe.rainier.core.Sampleable.prepare$(Sampleable.scala:13)
	at com.stripe.rainier.core.Sampleable$$anon$3.prepare(Sampleable.scala:63)
	at com.stripe.rainier.core.RandomVariable.sample(RandomVariable.scala:59)
	at com.stripe.rainier.example.DLM$.main(DLM.scala:73)
	at com.stripe.rainier.example.DLM.main(DLM.scala)
Caused by: java.lang.ClassNotFoundException: com.stripe.rainier.internal.asm.tree.MethodNode
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 34 more
```

**Comment by darrenjw** [comment]
Can you give us some more info on how you are running it? I've just tried running it on the current master and it seems fine.

**Comment by Zhen-hao** [comment]
Hi, I simply tried to run inside Intellij. Attached is the run config. 
![image](https://user-images.githubusercontent.com/10957195/41600107-4a2ae7d4-73d5-11e8-9203-5bd4033c64cf.png)

**Comment by Zhen-hao** [comment]
Similar result in sbt:

```
[IJ]sbt:root> runMain com.stripe.rainier.example.DLM
[info] Packaging /Users/zhenhao.li/workspace/rainier/target/scala-2.12/root_2.12-0.1.3-SNAPSHOT.jar ...
[info] Done packaging.
[info] Running com.stripe.rainier.example.DLM 
[error] (run-main-1) java.lang.ClassNotFoundException: com.stripe.rainier.example.DLM
[error] java.lang.ClassNotFoundException: com.stripe.rainier.example.DLM
[error] 	at java.lang.ClassLoader.findClass(ClassLoader.java:530)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[error] 	at sbt.internal.inc.classpath.ClasspathFilter.loadClass(ClassLoaders.scala:70)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[error] 	at java.lang.Class.forName0(Native Method)
[error] 	at java.lang.Class.forName(Class.java:348)
[error] 	at sbt.Run.getMainMethod(Run.scala:98)
[error] 	at sbt.Run.run0(Run.scala:86)
[error] 	at sbt.Run.execute$1(Run.scala:65)
[error] 	at sbt.Run.$anonfun$run$4(Run.scala:77)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] 	at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:10)
[error] 	at sbt.TrapExit$App.run(TrapExit.scala:252)
[error] 	at java.lang.Thread.run(Thread.java:745)
[error] java.lang.RuntimeException: Nonzero exit code: 1
[error] 	at sbt.Run$.executeTrapExit(Run.scala:124)
[error] 	at sbt.Run.run(Run.scala:77)
[error] 	at sbt.Defaults$.$anonfun$bgRunMainTask$6(Defaults.scala:1152)
[error] 	at sbt.Defaults$.$anonfun$bgRunMainTask$6$adapted(Defaults.scala:1147)
[error] 	at sbt.internal.BackgroundThreadPool.$anonfun$run$1(DefaultBackgroundJobService.scala:366)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] 	at scala.util.Try$.apply(Try.scala:209)
[error] 	at sbt.internal.BackgroundThreadPool$BackgroundRunnable.run(DefaultBackgroundJobService.scala:289)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error] 	at java.lang.Thread.run(Thread.java:745)
[error] (Compile / runMain) Nonzero exit code: 1
[error] Total time: 0 s, completed Jun 19, 2018 3:28:49 PM

```

**Comment by darrenjw** [comment]
You need to do "project rainierExample" to switch projects before attempting to run.

**Comment by Zhen-hao** [comment]
yes, of course. Sorry that I didn't look at the build.sbt for the structure.

**Comment by Zhen-hao** [comment]
but I thought Intellij would be able to figure out that because the module "rainierExample" was provided.
